version: '3'
services:
  gql-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/tt-gql-server
    ports:
      - 4000:4000
    environment:
      - PRISMA_MANAGEMENT_API_SECRET=${PRISMA_MANAGEMENT_API_SECRET}

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
             connector: postgres
             host: db
             port: 5432
             user: prisma
             password: 12345

  db:
    build:
      context: ./docker-bootstrap/db
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: travel-together-returns
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: prisma
